service:
  http:
    type: LoadBalancer
    port: 3000
gitea:
  admin:
    # DON'T use username admin as its reserved and gitea will 
    # fail to start
    username: demo
    password: demo@123
    email: admin@example.com
  config:
    server:
      PROTOCOL: http
      HTTP_PORT: 3000
      DOMAIN: ${GITEA_DOMAIN}
      ROOT_URL: http://${GITEA_DOMAIN}:3000/
    webhook:
      # since we will deploy to local networks we will disable 
      # TLS verify and allow all hosts
      ALLOWED_HOST_LIST: "*"
      SKIP_TLS_VERIFY: true
