service:
  type: NodePort
  port: 8080
  nodePort: 30980
  
extraSecretNamesForEnvFrom:
   # all the other as env variables are loaded via this secret
   # https://docs.drone.io/server/reference/
  - drone-demos-secret

env:
  DRONE_SERVER_HOST: drone-127.0.0.1.sslip.io:8080
  DRONE_GITEA_SKIP_VERIFY: true
  # https://docs.drone.io/server/provider/gitea/
  DRONE_GITEA_SERVER: http://gitea-127.0.0.1.sslip.io:3000/
  DRONE_SERVER_PROTO: http
  