service:
  type: LoadBalancer
  # has to be 8080 to traefik avoid waiting for LB IP
  port: 8080
  
extraSecretNamesForEnvFrom:
   # all the other as env variables are loaded via this secret
   # https://docs.drone.io/server/reference/
  - drone-demos-secret

env:
  DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
  DRONE_GITEA_SKIP_VERIFY: true
  # https://docs.drone.io/server/provider/gitea/
  DRONE_GITEA_SERVER: ${GITEA_URL}
  DRONE_SERVER_PROTO: http
  