service:
  type: NodePort
  nodePort: 30980
  
extraSecretNamesForEnvFrom:
   # all the other as env variables are loaded via this secret
   # https://docs.drone.io/server/reference/
  - drone-demos-secret

env:
  DRONE_SERVER_HOST: drone-127.0.0.1.sslip.io:8080
  